### ISSUE TITLE
Smartgrid check

### ISSUE THREAD

**Issue by Qvdpost** [minprog/theorie-check50#1]
De check50 crasht vanwege een error in het checken van het datatype van de json value. Met error: 

TypeError: Datatype Int64 not understood
In regel 79, in check_file
district = df.loc[0]['district'].astype('Int64)

**Comment by Jelleas** [comment]
https://github.com/minprog/theorie-check50/commit/2246180e03f7dc5a7336fb763ff3fca003de2c96#diff-00657f52c3e88a446ac85744e6631890bc57f3ac41caae21c91cf18122fa735b

fixed
